# Generated by Django 5.2 on 2025-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=5, unique=True)),
                ('salt_passwd', models.BinaryField(default=b'')),
                ('passwd', models.CharField(max_length=129)),
            ],
        ),
    ]
