# Generated by Django 5.2 on 2025-05-07 19:38

import database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_otp', models.CharField(max_length=8)),
                ('fecha_vencimiento', models.DateTimeField(default=database.models.default_expiration)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.usuario')),
            ],
        ),
    ]
