# Generated by Django 5.2.1 on 2025-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_contadorintentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('nombre_servidor', models.CharField(max_length=50, unique=True)),
                ('usuario', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('puerto', models.PositiveIntegerField(default=22)),
            ],
        ),
    ]
