# Generated by Django 5.2.1 on 2025-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='password',
            field=models.CharField(default='', max_length=129),
            preserve_default=False,
        ),
    ]
