# Generated by Django 5.2.1 on 2025-06-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_servidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='nombre_servidor',
        ),
        migrations.AddField(
            model_name='servidor',
            name='llave_ssh',
            field=models.TextField(default='', max_length=700),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.servidor')),
            ],
            options={
                'unique_together': {('nombre', 'servidor')},
            },
        ),
    ]
