# Generated by Django 5.2.1 on 2025-06-14 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_servidor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='salt_passwd',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='puerto',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puerto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('estado', models.CharField(default='desconocido', max_length=10)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.servidor')),
            ],
        ),
    ]
