# Generated by Django 5.2.1 on 2025-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_servidor_nombre_servidor_servidor_llave_ssh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='llave_ssh',
            field=models.TextField(max_length=4000),
        ),
    ]
