# Generated by Django 5.2.1 on 2025-06-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_servidor_salt_passwd_alter_servidor_puerto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(default='desconocido', max_length=20),
        ),
    ]
