# Generated by Django 5.2.1 on 2025-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_servidor_llave_ssh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='llave_ssh',
            field=models.BinaryField(),
        ),
    ]
