# Generated by Django 3.2.19 on 2025-06-14 04:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_contadorintentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('nombre_servidor', models.CharField(max_length=50, unique=True)),
                ('usuario', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('puerto', models.PositiveIntegerField(default=22)),
                ('llave_ssh', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]+$')])),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.servidor')),
            ],
            options={
                'unique_together': {('nombre', 'servidor')},
            },
        ),
    ]
